#!/bin/bash
echo Starting run...
echo Creating datasets...
python3 Create_Datasets.py
echo Preprocessing...
python3 Preprocessing.py
echo Initialising LSTM...
python3 LSTM.py
echo Setting up graphs...
python3 Graphs.py
echo Training model...
python3 -u Train.py 2>&1 | tee Results.txt
